### ISSUE TITLE
Getting just `number` or wrong answer for most types

### ISSUE THREAD

**Issue by TomerAberbach** [arielhs/ts-arithmetic#1]
```ts
import type { Add, Subtract } from 'ts-arithmetic'

// Evaluates to number instead of 3
type Sum = Add<1, 2>

// Evaluates to 0 instead of 1
type Difference = Subtract<3, 2>
```

Using `typescript@4.9.3` and `ts-arithmetic@0.1.1`.

**Comment by arielhs** [comment]
@TomerAberbach I have tested this out and don't seem to have any issues, can you create a codesandbox for me to see? (Also just a sanity check, have you correctly set your VS Code TypeScript version?)

**Comment by TomerAberbach** [comment]
You're right, turns out VS Code was using a different version of TypeScript than the one installed in `node_modules`. Thanks, and sorry for the noise!
